name: JScrewIt Node.js CI

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:
    branches: ['**']

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: '24'
    - run: npm install
    - run: npm run lint

  test:

    name: test (Node.js ${{ matrix.node-version }})

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
        - '0.10'
        - '0.12'
        - '4'
        - '6'
        - '8'
        - '10'
        - '12'
        - '14'
        - '16'
        - '18'
        - '20'
        - '22'
        - '24'
        - '26'

    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -D es6-promise mocha@3
    - run: npm test
